# Generated by Django 5.1.2 on 2024-12-05 20:49

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consommable',
            fields=[
                ('id_consommable', models.AutoField(primary_key=True, serialize=False)),
                ('nom_consommable', models.CharField(max_length=80)),
                ('categorie', models.CharField(max_length=80)),
                ('descrition', models.TextField(blank=True, null=True)),
                ('prix_unitaire', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('nom_service', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nom_utilisateur', models.CharField(max_length=50, unique=True)),
                ('numero_utilisateur', models.CharField(max_length=10, unique=True)),
                ('est_admin', models.BooleanField(default=False)),
                ('service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='Consommation.service')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_stock', models.IntegerField(default=0)),
                ('date_maj_stock', models.DateField(auto_now=True)),
                ('consommable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Consommation.consommable')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id_conso', models.AutoField(primary_key=True, serialize=False)),
                ('date_conso', models.DateField(auto_now=True)),
                ('quantite_conso', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Consommation.service')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Consommation.stock')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
