# Generated by Django 5.1.2 on 2024-10-23 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consommation', '0004_consommable_stock_consommation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='utilisateur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
