# Generated by Django 5.1.2 on 2024-10-28 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consommation', '0005_stock_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommation',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Consommation.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consommation',
            name='utilisateur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
