# Generated by Django 5.1.2 on 2024-11-22 23:33

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consommation', '0006_consommation_service_consommation_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommable',
            name='descrition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consommable',
            name='prix_unitaire',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consommation',
            name='date_conso',
            field=models.DateField(verbose_name=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Consommation.service'),
        ),
    ]
