# Generated by Django 5.1.2 on 2024-11-28 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consommation', '0007_consommable_descrition_consommable_prix_unitaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Consommation.service'),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Consommation.stock'),
        ),
        migrations.AlterField(
            model_name='consommation',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stock',
            name='consommable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Consommation.consommable'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='Consommation.service'),
        ),
    ]
