# Generated by Django 5.1.2 on 2024-11-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consommation', '0008_alter_consommation_service_alter_consommation_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommation',
            name='date_conso',
            field=models.DateField(auto_now=True),
        ),
    ]
